export const PLAN_FEATURES = {
  CONTACT_OWNER_LIMIT: "CONTACT_OWNER_LIMIT",
  CONTACT_BUYER_LIMIT: "CONTACT_BUYER_LIMIT",
  PROPERTY_LISTING_LIMIT: "PROPERTY_LISTING_LIMIT",
  PROPERTY_VISIBILITY_PERCENT: "PROPERTY_VISIBILITY_PERCENT",
  TOP_LISTING_DAYS: "TOP_LISTING_DAYS",

  PROPERTY_COMPARISON: "PROPERTY_COMPARISON",
  LEAD_DASHBOARD: "LEAD_DASHBOARD",
  CRM_ACCESS: "CRM_ACCESS",
  TEAM_MEMBERS: "TEAM_MEMBERS",

  AREA_INSIGHTS_LEVEL: "AREA_INSIGHTS_LEVEL",
  BUYER_REACH_PERCENT: "BUYER_REACH_PERCENT",
};
