export const plans = [
  // ---------------- RENTAL subscription ----------------
  {
    code: "RENTAL_FREE",
    userType: "owner",
    category: "rent_view",
    tier: "free",
    name: "Free",
    price: 0,
    features: {
      CONTACT_OWNER_LIMIT: 2,
    },
  },
  {
    code: "RENTAL_TIER_1",
    userType: "owner",
    category: "rent_view",
    tier: "tier1",
    name: "Rental Assist",
    price: 699,
    features: {
      CONTACT_OWNER_LIMIT: 4,
    },
  },
  {
    code: "RENTAL_TIER_2",
    userType: "owner",
    category: "rent_view",
    tier: "tier2",
    name: "Rental Guide",
    price: 1499,
    features: {
      CONTACT_OWNER_LIMIT: 10,
      PROPERTY_COMPARISON: true,
      LEAD_DASHBOARD: true,
    },
  },
  {
    code: "RENTAL_TIER_3",
    userType: "owner",
    category: "rent_view",
    tier: "tier3",
    name: "Rental Assure",
    price: 2999,
    features: {
      CONTACT_OWNER_LIMIT: 20,
      PROPERTY_COMPARISON: true,
      LEAD_DASHBOARD: true,
    },
  },

  // ---------------- BUYER subscription ----------------
  {
    code: "BUYER_FREE",
    userType: "owner",
    category: "buy",
    tier: "free",
    name: "Buyer Free",
    price: 0,
    features: {
      CONTACT_OWNER_LIMIT: 2,
    },
  },
  {
    code: "BUYER_RENT_TIER_1",
    userType: "owner",
    category: "buy",
    tier: "tier1",
    name: "Buyer Easy",
    price: 499,
    features: {
      CONTACT_OWNER_LIMIT: 4,
    },
  },
  {
    code: "BUYER_RENT_TIER_2",
    userType: "owner",
    category: "buy",
    tier: "tier2",
    name: "Buyer Core",
    price: 999,
    features: {
      CONTACT_OWNER_LIMIT: 10,
      PROPERTY_COMPARISON: true,
      LEAD_DASHBOARD: true,
    },
  },
  {
    code: "BUYER_RENT_TIER_3",
    userType: "owner",
    category: "buy",
    tier: "tier3",
    name: "Buyer Advance",
    price: 1999,
    features: {
      CONTACT_OWNER_LIMIT: 20,
      PROPERTY_COMPARISON: true,
      LEAD_DASHBOARD: true,
    },
  },

  // ---------------- OWNER SELL ----------------
  {
    code: "OWNER_SELL_FREE",
    userType: "owner",
    category: "sell",
    tier: "free",
    name: "Free",
    price: 0,
    features: {
      PROPERTY_LISTING_LIMIT: 2,
      ENQUIRY_LIMIT: 2,
      TOP_LISTING_DAYS: 0,
    },
  },
  {
    code: "OWNER_SELL_TIER_1",
    userType: "owner",
    category: "sell",
    tier: "tier1",
    name: "Owner Access",
    price: 499,
    features: {
      PROPERTY_LISTING_LIMIT: 10,
      ENQUIRY_LIMIT: 10,
      TOP_LISTING_DAYS: 5,
    },
  },
  {
    code: "OWNER_SELL_TIER_2",
    userType: "owner",
    category: "sell",
    tier: "tier2",
    name: "Owner Advantage",
    price: 999,
    features: {
      PROPERTY_LISTING_LIMIT: 15,
      ENQUIRY_LIMIT: 15,
      TOP_LISTING_DAYS: 10,
    },
  },
  {
    code: "OWNER_SELL_TIER_3",
    userType: "owner",
    category: "sell",
    tier: "tier3",
    name: "Owner Ultra",
    price: 1999,
    features: {
      PROPERTY_LISTING_LIMIT: 20,
      ENQUIRY_LIMIT: 20,
      TOP_LISTING_DAYS: 5,
    },
  },

  // ---------------- OWNER RENT ----------------
  {
    code: "OWNER_RENT_FREE",
    userType: "owner",
    category: "rent",
    tier: "free",
    name: "Free",
    price: 0,
    features: {
      PROPERTY_LISTING_LIMIT: 2,
      ENQUIRY_LIMIT: 2,
      TOP_LISTING_DAYS: 0,
    },
  },
  {
    code: "OWNER_RENT_TIER_1",
    userType: "owner",
    category: "rent",
    tier: "tier1",
    name: "Owner Access",
    price: 499,
    features: {
      PROPERTY_LISTING_LIMIT: 10,
      ENQUIRY_LIMIT: 10,
      TOP_LISTING_DAYS: 5,
    },
  },
  {
    code: "OWNER_RENT_TIER_2",
    userType: "owner",
    category: "rent",
    tier: "tier2",
    name: "Owner Advantage",
    price: 999,
    features: {
      PROPERTY_LISTING_LIMIT: 15,
      ENQUIRY_LIMIT: 15,
      TOP_LISTING_DAYS: 10,
    },
  },
  {
    code: "OWNER_RENT_TIER_3",
    userType: "owner",
    category: "rent",
    tier: "tier3",
    name: "Owner Ultra",
    price: 1999,
    features: {
      PROPERTY_LISTING_LIMIT: 20,
      ENQUIRY_LIMIT: 20,
      TOP_LISTING_DAYS: 20,
    },
  },

  // ---------------- AGENT PLANS ----------------
  {
    code: "AGENT_FREE",
    userType: "agent",
    category: "both",
    tier: "free",
    name: "Free",
    price: 0,
    durationDays: 30,
    features: {
      PROPERTY_LISTING_LIMIT: 20,
      BUYER_REACH_PERCENT: 50,
      ENQUIRY_LIMIT: 30,
      TOP_LISTING_DAYS: 0,
      TEAM_MEMBERS: 0,
    },
  },
  {
    code: "AGENT_PRO_RENT",
    userType: "agent",
    category: "both",
    tier: "tier1",
    name: "Pro Rent",
    price: 1999,
    durationDays: 30,
    features: {
      PROPERTY_LISTING_LIMIT: 40,
      BUYER_REACH_PERCENT: 100,
      ENQUIRY_LIMIT: 50,
      TOP_LISTING_DAYS: 5,
      TEAM_MEMBERS: 1,
    },
  },
  {
    code: "AGENT_PRO_SELL",
    userType: "agent",
    category: "both",
    tier: "tier2",
    name: "Pro Sell",
    price: 2999,
    durationDays: 40,
    features: {
      PROPERTY_LISTING_LIMIT: 40,
      BUYER_REACH_PERCENT: 100,
      ENQUIRY_LIMIT: 50,
      TOP_LISTING_DAYS: 5,
      TEAM_MEMBERS: 1,
    },
  },
  {
    code: "AGENT_ELITE",
    userType: "agent",
    category: "both",
    tier: "tier3",
    name: "Elite",
    price: 5999,
    durationDays: 120,
    features: {
      PROPERTY_LISTING_LIMIT: 80,
      BUYER_REACH_PERCENT: 100,
      ENQUIRY_LIMIT: 100,
      TOP_LISTING_DAYS: 20,
      TEAM_MEMBERS: 5,
    },
  },
];
