import express from "express";
import Role from "../models/roleModel";
import { ALL_PERMISSIONS } from "../constants/permissionCatalog";

const router = express.Router();

router.post("/seed-roles", async (_req, res) => {
  try {
    // 1️⃣ Define all permissions in one place
    const LEGACY_PERMISSIONS = [
      "project:create",
      "project:view",
      "project:edit",
      "project:update",
      "project:delete",
      "project:transfer",

      "lead:create",
      "lead:view",
      "lead:edit",
      "lead:update",
      "lead:delete",
      "lead:assign",
      "lead:import",
      "lead:download",

      "agent:create",
      "agent:view",
      "agent:edit",
      "agent:delete",

      "team:create",
      "team:view",
      "team:update",
      "team:delete",

      "role:create",
      "role:view",
      "role:update",
      "role:delete",

      "blog:create",
      "blog:view",
      "blog:edit",
      "blog:delete",
    ];

    // 2️⃣ Define roles
    const roles = [
      {
        name: "super_admin",
        label: "Super Admin",
        permissions: ALL_PERMISSIONS,
        roleType: "system",
        isProtected: true,
      },
      {
        name: "admin",
        label: "Admin",
        permissions: [
          "dashboard:view",
          "dashboard:view_analytics",
          "project:create",
          "project:view",
          "project:edit",
          "project:delete",
          "project:approve",
          "residential:view",
          "residential:update",
          "commercial:view",
          "commercial:update",
          "land:view",
          "land:update",
          "agricultural:view",
          "agricultural:update",
          "lead:create",
          "lead:view",
          "lead:edit",
          "lead:delete",
          "lead:assign",
          "user:view",
          "builder:view",
          "agent:view",
          "agent:edit",
          "team:view",
          "ticket:view",
          "ticket:update",
          "ticket:assign",
          "ticket_dashboard:view",
          "blog:view",
          "location:view",
        ],
        roleType: "system",
        isProtected: true,
      },
      {
        name: "sales_manager",
        label: "Sales Manager",
        permissions: [
          "project:view",
          "project:edit",
          "project:create",
          "project:approve",
          "project:reject",
          "lead:view",
          "lead:delete",
          "lead:assign",
        ],
      },
      {
        name: "regional_manager",
        label: "Regional Managers",
        permissions: ALL_PERMISSIONS,
      },
      {
        name: "sales_agent",
        label: "Sales Executives",
        permissions: [
          "project:view",
          "project:create",
          "lead:view",
          "lead:edit",
          "lead:delete",
        ],
      },
      {
        name: "user",
        label: "User",
        permissions: ["project:view", "project:create"],
        roleType: "system",
        isProtected: true,
      },
      {
        name: "agent",
        label: "Agent",
        permissions: ["project:view", "lead:view", "lead:edit", "agent:view"],
        roleType: "system",
        isProtected: true,
      },
      {
        name: "builder",
        label: "Builder",
        permissions: [
          "project:create",
          "project:view",
          "project:edit",
          "lead:delete",
          "agent:create",
          "agent:view",
          "agent:edit",
        ],
        roleType: "system",
        isProtected: true,
      },
      {
        name: "builder_staff",
        label: "Builder Staff",
        permissions: [],
        roleType: "system",
        isProtected: true,
      },
      {
        name: "ceo",
        label: "CEO",
        permissions: [
          "dashboard:view",
          "dashboard:view_analytics",
          "dashboard:view_reports",
          "dashboard:export",
          "project:view",
          "project:create",
          "project:approve",
          "project:reject",
          "residential:view",
          "commercial:view",
          "land:view",
          "agricultural:view",
          "lead:view",
          "user:view",
          "builder:view",
          "agent:view",
          "team:view",
          "payment:view",
          "payment:view_reports",
          "subscription:view",
          "subscription:view_history",
          "ticket:view",
          "ticket:view_summary",
          "ticket_dashboard:view",
          "ticket_dashboard:view_trends",
          "blog:view",
          "email_campaign:view",
          "whatsapp_campaign:view",
          "role:view",
        ],
        roleType: "system",
        isProtected: true,
      },
      {
        name: "accounts",
        label: "Accounts",
        permissions: [
          "dashboard:view",
          "payment:view",
          "subscription:view",
          "project:view",
          "lead:view",
        ],
      },
      {
        name: "marketing_head",
        label: "Marketing Head",
        permissions: [
          "dashboard:view",
          "project:view",
          "residential:view",
          "commercial:view",
          "land:view",
          "agricultural:view",
          "lead:create",
          "lead:view",
          "lead:edit",
          "lead:assign",
          "lead:import",
          "lead:download",
          "blog:create",
          "blog:view",
          "blog:edit",
          "email_campaign:view",
          "email_campaign:create",
          "whatsapp_campaign:view",
          "whatsapp_campaign:create",
          "notification:view",
        ],
      },
      {
        name: "digital_marketing",
        label: "Digital Marketing",
        permissions: [
          "dashboard:view",
          "project:view",
          "lead:create",
          "lead:view",
          "lead:edit",
          "lead:delete",
          "lead:assign",
          "lead:import",
          "lead:download",
          "blog:create",
          "blog:view",
          "blog:edit",
          "blog:delete",
          "email_campaign:view",
          "whatsapp_campaign:view",
        ],
      },
      {
        name: "content_team",
        label: "Content Team",
        permissions: [
          "dashboard:view",
          "project:view",
          "residential:view",
          "commercial:view",
          "land:view",
          "agricultural:view",
          "blog:create",
          "blog:view",
          "blog:edit",
          "blog:delete",
          "lead:view",
        ],
      },
      {
        name: "customer_support_head",
        label: "Customer Support Head",
        permissions: [
          "dashboard:view",
          "project:view",
          "residential:view",
          "commercial:view",
          "land:view",
          "agricultural:view",
          "lead:view",
          "lead:edit",
          "lead:update_status",
          "lead:add_note",
          "user:view",
          "ticket:create",
          "ticket:view",
          "ticket:update",
          "ticket:assign",
          "ticket:update_status",
          "ticket:update_priority",
          "ticket:add_comment",
          "ticket:view_summary",
          "ticket_dashboard:view",
          "ticket_dashboard:view_trends",
          "ticket_dashboard:view_agent_performance",
          "ticket_attachment:create",
          "ticket_attachment:view",
        ],
      },
      {
        name: "customer_care",
        label: "Customer Care",
        permissions: [
          "dashboard:view",
          "project:view",
          "project:create",
          "residential:view",
          "commercial:view",
          "land:view",
          "agricultural:view",
          "lead:view",
          "lead:edit",
          "lead:update_status",
          "lead:add_note",
          "user:view",
          "ticket:create",
          "ticket:view",
          "ticket:update",
          "ticket:update_status",
          "ticket:update_priority",
          "ticket:add_comment",
          "ticket:view_summary",
          "ticket_dashboard:view",
          "ticket_dashboard:view_trends",
          "ticket_attachment:create",
          "ticket_attachment:view",
        ],
      },
      {
        name: "customer_care_executive",
        label: "Customer Care Executive",
        permissions: [
          "dashboard:view",
          "project:view",
          "project:create",
          "residential:view",
          "commercial:view",
          "land:view",
          "agricultural:view",
          "lead:view",
          "lead:edit",
          "lead:update_status",
          "lead:add_note",
          "user:view",
          "ticket:create",
          "ticket:view",
          "ticket:update",
          "ticket:update_status",
          "ticket:update_priority",
          "ticket:add_comment",
          "ticket:view_summary",
          "ticket_dashboard:view",
          "ticket_dashboard:view_trends",
          "ticket_attachment:create",
          "ticket_attachment:view",
        ],
      },
      {
        name: "customer_care_executives",
        label: "Customer Care Executives",
        permissions: [
          "dashboard:view",
          "project:view",
          "project:create",
          "residential:view",
          "commercial:view",
          "land:view",
          "agricultural:view",
          "lead:view",
          "lead:edit",
          "lead:update_status",
          "lead:add_note",
          "user:view",
          "ticket:create",
          "ticket:view",
          "ticket:update",
          "ticket:update_status",
          "ticket:update_priority",
          "ticket:add_comment",
          "ticket:view_summary",
          "ticket_dashboard:view",
          "ticket_dashboard:view_trends",
          "ticket_attachment:create",
          "ticket_attachment:view",
        ],
      },
      {
        name: "relationship_manager",
        label: "Relationship Manager",
        permissions: [
          "project:view",
          "project:create",
          "lead:view",
          "lead:edit",
          "lead:assign",
          "agent:view",
        ],
      },
      {
        name: "operations_head",
        label: "Operations Head",
        permissions: ["dashboard:view", "team:view", "user:view", "role:view", "project:view", "lead:view"],
      },
      {
        name: "business_development_head",
        label: "Business Development Head",
        permissions: ["dashboard:view", "team:view", "project:view", "lead:view", "lead:assign"],
      },
      {
        name: "business_development_manager",
        label: "Business Development Manager",
        permissions: ["dashboard:view", "project:view", "lead:view", "lead:edit"],
      },
      {
        name: "team_lead",
        label: "Customer Support Team Leads",
        permissions: [
          "dashboard:view",
          "user:view",
          "ticket:view",
          "ticket:update",
          "ticket:assign",
          "ticket_dashboard:view",
          "lead:view",
        ],
      },
      {
        name: "accounts",
        label: "Accounts",
        permissions: ["dashboard:view", "payment:view", "subscription:view", "project:view"],
      },
      {
        name: "accounts_finance",
        label: "Accounts",
        permissions: ["dashboard:view", "payment:view", "subscription:view", "project:view"],
      },
      {
        name: "legal_compliance",
        label: "Legal",
        permissions: ["dashboard:view", "project:view", "user:view", "builder:view"],
      },
      {
        name: "hr_administration",
        label: "HR",
        permissions: ["dashboard:view", "user:view", "team:view", "role:view"],
      },
      {
        name: "social_media",
        label: "Social Media",
        permissions: ["dashboard:view", "blog:view", "blog:create", "blog:edit", "whatsapp_campaign:view"],
      },
      {
        name: "creative_team",
        label: "Creative Team",
        permissions: ["dashboard:view", "blog:view", "blog:create", "blog:edit", "project:view"],
      },
      {
        name: "technical_support_head",
        label: "Technical Support Head",
        permissions: ["dashboard:view", "ticket:view", "ticket:assign", "ticket_dashboard:view", "user:view"],
      },
      {
        name: "technical_support_team",
        label: "Technical Support Team",
        permissions: ["dashboard:view", "ticket:view", "ticket:update", "ticket:add_comment"],
      },
      {
        name: "founder",
        label: "Founder",
        permissions: ["dashboard:view", "dashboard:view_analytics", "team:view", "role:view", "user:view"],
      },
    ];

    // Parent links for organisation hierarchy (canonical tree).
    // Super Admin → CEO | Operations Head → (BD / Support / Marketing / Accounts / Legal / HR / Tech)
    const parentByRole: Record<string, string> = {
      ceo: "super_admin",
      founder: "super_admin",
      admin: "super_admin",
      operations_head: "super_admin",
      business_development_head: "operations_head",
      regional_manager: "business_development_head",
      business_development_manager: "regional_manager",
      sales_manager: "regional_manager",
      sales_agent: "regional_manager",
      customer_support_head: "operations_head",
      team_lead: "customer_support_head",
      customer_care: "team_lead",
      customer_care_executive: "team_lead",
      customer_care_executives: "team_lead",
      relationship_manager: "team_lead",
      marketing_head: "operations_head",
      digital_marketing: "marketing_head",
      social_media: "marketing_head",
      content_team: "marketing_head",
      creative_team: "marketing_head",
      accounts: "operations_head",
      accounts_finance: "operations_head",
      legal_compliance: "operations_head",
      hr_administration: "operations_head",
      technical_support_head: "operations_head",
      technical_support_team: "technical_support_head",
    };

    // 3️⃣ Upsert roles (create if not exist, update if exist)
    for (const role of roles) {
      await Role.findOneAndUpdate({ name: role.name }, role, { upsert: true, new: true, setDefaultsOnInsert: true });
    }

    // 4️⃣ Wire parentRoleId after all roles exist
    const allRoles = await Role.find({ name: { $in: Object.keys(parentByRole).concat(Object.values(parentByRole)) } })
      .select("_id name")
      .lean();
    const idByName = new Map(allRoles.map((role) => [role.name, role._id]));
    for (const [childName, parentName] of Object.entries(parentByRole)) {
      const childId = idByName.get(childName);
      const parentId = idByName.get(parentName);
      if (!childId || !parentId) continue;
      await Role.updateOne({ _id: childId }, { $set: { parentRoleId: parentId } });
    }

    res.json({ message: "Roles seeded successfully with hierarchy parents" });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Failed to seed roles" });
  }
});

export default router;
