// eslint.config.ts (or eslint.config.mjs)
import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

export default defineConfig([
  // Next.js recommended rules
  ...nextVitals,
  ...nextTs,

  // Global ignores – keep ESLint out of build artifacts / deps
  globalIgnores([
    // Next.js / build outputs
    ".next/**",
    "out/**",
    "build/**",
    "dist/**",

    // Dependencies
    "node_modules/**",

    // Generated by Next
    "next-env.d.ts",

    // Vercel / local env stuff (if present inside this folder)
    ".vercel/**",
  ]),
]);
