// // eslint.config.ts (or eslint.config.mjs)
// import { defineConfig, globalIgnores } from "eslint/config";
// import nextVitals from "eslint-config-next/core-web-vitals";
// import nextTs from "eslint-config-next/typescript";

// export default defineConfig([
//   // Next.js recommended rules
//   ...nextVitals,
//   ...nextTs,

//   // Global ignores – keep ESLint out of build artifacts / deps
//   globalIgnores([
//     // Next.js / build outputs
//     ".next/**",
//     "out/**",
//     "build/**",
//     "dist/**",

//     // Dependencies
//     "node_modules/**",

//     // Generated by Next
//     "next-env.d.ts",

//     // Vercel / local env stuff (if present inside this folder)
//     ".vercel/**",
//   ]),
// ]);


import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),

   // Rule overrides
  {
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      "@typescript-eslint/no-explicit-any": "on",         // disable 'any' errors
      "@typescript-eslint/no-unused-vars": ["warn"],       // change to warning (optional)
      "no-unused-vars": "on",                              // in case base rules conflict
    },
  },
];

export default eslintConfig;