const { cpSync, existsSync, mkdirSync, writeFileSync } = require("node:fs");
const { resolve } = require("node:path");

const source = resolve(__dirname, "../src/assets");
const destination = resolve(__dirname, "../dist/assets");

if (existsSync(source)) {
  mkdirSync(destination, { recursive: true });
  cpSync(source, destination, { recursive: true, force: true });
}

/**
 * tsconfig rootDir is ../../ (backend), so compiled output lands at
 * dist/services/property-service/src/server.js. Keep a stable entry at
 * dist/server.js so older process managers still boot the real app.
 */
const nestedServer = resolve(
  __dirname,
  "../dist/services/property-service/src/server.js",
);
const legacyEntry = resolve(__dirname, "../dist/server.js");

if (existsSync(nestedServer)) {
  writeFileSync(
    legacyEntry,
    [
      '"use strict";',
      "// Auto-generated by scripts/copy-assets.js — do not edit.",
      'require("./services/property-service/src/server.js");',
      "",
    ].join("\n"),
    "utf8",
  );
}
